// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvn6JKbdCDnuyCQmPNX2Y3DeGxiy9AEI8',
    appId: '1:173395629793:web:de78823e922fea582a49a0',
    messagingSenderId: '173395629793',
    projectId: 'mediapp-be4a6',
    authDomain: 'mediapp-be4a6.firebaseapp.com',
    storageBucket: 'mediapp-be4a6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbPAeDvZOLXxRGBJyQQYrSShtbZcVo2Ac',
    appId: '1:173395629793:android:5fbc5e3e346186102a49a0',
    messagingSenderId: '173395629793',
    projectId: 'mediapp-be4a6',
    storageBucket: 'mediapp-be4a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA-sfBjDZtM9_QWKekZjE8St3XI8jkgEg',
    appId: '1:173395629793:ios:f3e5df3384e6f7bd2a49a0',
    messagingSenderId: '173395629793',
    projectId: 'mediapp-be4a6',
    storageBucket: 'mediapp-be4a6.firebasestorage.app',
    iosBundleId: 'com.example.mediApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA-sfBjDZtM9_QWKekZjE8St3XI8jkgEg',
    appId: '1:173395629793:ios:f3e5df3384e6f7bd2a49a0',
    messagingSenderId: '173395629793',
    projectId: 'mediapp-be4a6',
    storageBucket: 'mediapp-be4a6.firebasestorage.app',
    iosBundleId: 'com.example.mediApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvn6JKbdCDnuyCQmPNX2Y3DeGxiy9AEI8',
    appId: '1:173395629793:web:deb1ea942482c0b32a49a0',
    messagingSenderId: '173395629793',
    projectId: 'mediapp-be4a6',
    authDomain: 'mediapp-be4a6.firebaseapp.com',
    storageBucket: 'mediapp-be4a6.firebasestorage.app',
  );
}
